TicketsDemo/Models/CreateTicketModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TicketsDemo.Models
{
    public class CreateTicketModel
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int ReservationId { get; set; }
    }
}

TicketsDemo/Models/IndexPageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TicketsDemo.Data.Entities;

namespace TicketsDemo.Models
{
    public class IndexPageViewModel
    {
        public DateTime ScheduleStart { get; set; }
        public DateTime ScheduleEnd { get; set; }
        public List<Run> Runs { get; set; }
        public Dictionary<int,Train> Trains { get; set; }
    }
}

TicketsDemo/Models/ReservationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TicketsDemo.Data.Entities;

namespace TicketsDemo.Models
{
    public class ReservationViewModel
    {
        public Reservation Reservation { get; set; }
        public List<PriceComponent> PriceComponents { get; set; }
    }
}

TicketsDemo/Models/RunViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TicketsDemo.Data.Entities;

namespace TicketsDemo.Models
{
    public class RunViewModel
    {
        public Run Run { get; set; }
        public List<int> ReservedPlaces { get; set; }
    }
}

TicketsDemo/Models/TrainDetailsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TicketsDemo.Data.Entities;

namespace TicketsDemo.Models
{
    public class TrainDetailsViewModel
    {
        public DateTime ScheduleStart { get; set; }
        public DateTime ScheduleEnd { get; set; }
        public Train Train { get; set; }
        public List<Run> Runs { get; set; }
        public List<DateTime> AvailableDates { get; set; }
    }
}

TicketsDemo/Controllers/RunController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicketsDemo.Data.Repositories;
using TicketsDemo.Domain.Interfaces;
using TicketsDemo.Models;

namespace TicketsDemo.Controllers
{
    public class RunController : Controller
    {
        private ITicketRepository _tickRepo;
        private IRunRepository _runRepo;
        private IReservationService _resServ;
        private ITicketService _tickServ;
        private IPriceCalculationStrategy _priceCalc;

        public RunController(ITicketRepository tick, IRunRepository run, 
            IReservationService resServ,
            ITicketService tickServ,IPriceCalculationStrategy priceCalcStrategy) {
            _tickRepo = tick;
            _runRepo = run;
            _resServ = resServ;
            _tickServ = tickServ;
            _priceCalc = priceCalcStrategy;
        }

        public ActionResult Index(int id) {
            var run = _runRepo.GetRunDetails(id);
            var model = new RunViewModel() { 
                 Run = run,
                 ReservedPlaces = run.Places.Where(p => _resServ.PlaceIsOccupied(p)).Select(p => p.Id).ToList()
            };

            return View(model);
        }

        public ActionResult ReservePlace(int placeId,int runId) {
            var run = _runRepo.GetRunDetails(runId);
            var place = run.Places.Single(p => p.Id == placeId);

            var reservation = _resServ.Reserve(place);

            var model = new ReservationViewModel()
            {
                Reservation = reservation,
                PriceComponents = _priceCalc.CalculatePrice(reservation)
            };

            return View(model);
        }

        [HttpPost]
        public ActionResult CreateTicket(CreateTicketModel model)
        {
            var tick = _tickServ.CreateTicket(model.ReservationId,model.FirstName,model.LastName);
            return RedirectToAction("Ticket", new { id = tick.Id });
        }

        public ActionResult Ticket(int id)
        {
            return View(_tickRepo.Get(id));
        }

    }
}

TicketsDemo/Controllers/ScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TicketsDemo.Data.Repositories;
using TicketsDemo.Domain.Interfaces;
using TicketsDemo.Models;

namespace TicketsDemo.Controllers
{
    public class ScheduleController : Controller
    {
        private ISchedule _schedule;
        private ITrainRepository _trainRepo;
        private IRunRepository _runRepo;

        public ScheduleController(ISchedule schedule, ITrainRepository trainRepo, IRunRepository runRepo) {
            _schedule = schedule;
            _trainRepo = trainRepo;
            _runRepo = runRepo;
        }

        public ActionResult Index()
        {
            var startDate = DateTime.Now;
            var endDate = startDate.AddMonths(1);
            var model = new IndexPageViewModel()
            {
                ScheduleStart = startDate,
                ScheduleEnd = endDate,
                Runs = _runRepo.GetRuns(startDate, endDate),
                Trains = _trainRepo.GetAllTrains().ToDictionary(x => x.Id)
            };

            return View(model);
        }

        public ActionResult Train(int id) {
            var startDate = DateTime.Now;
            var endDate = startDate.AddMonths(1);
            var model = new TrainDetailsViewModel()
            {
                ScheduleStart = startDate,
                ScheduleEnd = endDate,
                Runs = _runRepo.GetRuns(startDate, endDate,id),
                Train = _trainRepo.GetTrainDetails(id),
                AvailableDates = _schedule.GetAvailableDatesForNewRun(id,startDate,endDate)
            };
            
            return View(model);      
        }
        
        public ActionResult CreateRun(int trainId, DateTime date) {
            _schedule.CreateRun(trainId, date);
            return RedirectToAction("Train", new { id = trainId });
        }

        public ActionResult DeleteRun(int id)
        {
            _schedule.DeleteRun(id);
            return RedirectToAction("Train", new { id = id });
        }
    }
}

TicketsDemo/Views/Run/Index.cshtml
@model TicketsDemo.Models.RunViewModel

@{
    ViewBag.Title = "Run details";
}

<h2>Train @Model.Run.Train.Number (@Model.Run.Train.StartLocation - @Model.Run.Train.EndLocation)</h2>
<h4>Run starts at @Model.Run.Date.ToShortDateString()</h4>

<h2>Available Places</h2>

@foreach (var place in Model.Run.Places)
{
    if (Model.ReservedPlaces.Contains(place.Id))
    {
        @place.Place.Number;
    }else{
        <a href="@Url.Action("ReservePlace",new{placeId=place.Id,runId=Model.Run.Id})">@place.Place.Number</a>
    }
}

TicketsDemo/Views/Run/ReservePlace.cshtml
@model TicketsDemo.Models.ReservationViewModel

@{
    ViewBag.Title = "Run details";
}

<h2>Train @Model.Reservation.PlaceInRun.Run.Train.Number (@Model.Reservation.PlaceInRun.Run.Train.StartLocation - @Model.Reservation.PlaceInRun.Run.Train.EndLocation)</h2>
<h4>Run starts at @Model.Reservation.PlaceInRun.Run.Date.ToShortDateString()</h4>

<h2>the place @Model.Reservation.PlaceInRun.Place.Number is reserved for you for</h2>

<h4>Price:</h4>
@foreach (var pc in Model.PriceComponents) { 
    <span>@pc.Name:@pc.Value$</span><br />
}

@using (Html.BeginForm("CreateTicket","Run"))
{ 
    <input type="hidden" value="@Model.Reservation.Id" name="ReservationId" id="ReserevationId"/>
    <table>
        <tr>
            <td>First Name</td>
            <td><input type="text" name="FirstName" id="FirstName" /></td>
        </tr>
        <tr>
            <td>Last Name</td>
            <td><input type="text" name="LastName" id="LastName" /></td>
        </tr>
    </table>
    <input type="submit" value="submit"/>
}

<!--public string FirstName { get; set; }
        public string LastName { get; set; }
        public int ReservationId { get; set; }-->

TicketsDemo/Views/Run/ticket.cshtml
@model TicketsDemo.Data.Entities.Ticket

@{
    ViewBag.Title = "Ticket details";
}

<h2>Train @Model.Reservation.PlaceInRun.Run.Train.Number (@Model.Reservation.PlaceInRun.Run.Train.StartLocation - @Model.Reservation.PlaceInRun.Run.Train.EndLocation)</h2>
<h4>Run starts at @Model.Reservation.PlaceInRun.Run.Date.ToShortDateString()</h4>

<h2>ticket is for place @Model.Reservation.PlaceInRun.Place.Number</h2>

<h4>Price:</h4>
@foreach (var pc in Model.PriceComponents) { 
    <span>@pc.Name:@pc.Value$</span><br />
}

<!--public string FirstName { get; set; }
        public string LastName { get; set; }
        public int ReservationId { get; set; }-->

TicketsDemo/Views/Schedule/Index.cshtml
@model TicketsDemo.Models.IndexPageViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Available Trains</h2>
@foreach (var train in Model.Trains) { 
    <a href="@Url.Action("Train",new {id = train.Value.Id})">@train.Value.Number (@train.Value.StartLocation - @train.Value.EndLocation)</a><br />
}

<h2>Display train runs schedule between @Model.ScheduleStart.ToShortDateString() and @Model.ScheduleEnd.ToShortDateString()</h2>

@foreach (var run in Model.Runs.OrderBy(m => m.Date)) { 
    <a href="@Url.Action("Index","Run",new {id = run.Id})">@run.Date.ToShortDateString(),train:@Model.Trains[run.TrainId].Number</a> <br />
}

TicketsDemo/Views/Schedule/Train.cshtml
@model TicketsDemo.Models.TrainDetailsViewModel

@{
    ViewBag.Title = "Index";
}

<h2>Train @Model.Train.Number (@Model.Train.StartLocation - @Model.Train.EndLocation)</h2>
@foreach (var carriage in Model.Train.Carriages) { 
   <h4>@carriage.Type.ToString()</h4>
    foreach (var place in carriage.Places) { 
        @place.Number<text>,</text>
    }
}

<h2>Schedule between the @Model.ScheduleStart.ToShortDateString() and @Model.ScheduleEnd.ToShortDateString()</h2>

@foreach (var run in Model.Runs.OrderBy(m => m.Date)) { 
    <a href="@Url.Action("Index","Run",new {id = run.Id})">@run.Date.ToShortDateString(),train:@Model.Train.Number</a> <br />
}

<h2>Create new Run</h2>
@foreach (var date in Model.AvailableDates) { 
    <a href="@Url.Action("CreateRun",new {trainId = Model.Train.Id,date=date})">at @date.ToShortDateString()</a>
}